import { MetadataRoute } from 'next'

export function GET(): Response {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://druginfo.example.com'
  
  const robotsTxt = `# Drug Information Platform Robots.txt
# Generated by Next.js

User-agent: *
Allow: /
Allow: /drugs/
Allow: /search
Allow: /api/og/*

# Block admin and internal pages
Disallow: /api/
Disallow: /_next/
Disallow: /admin/
Disallow: /dashboard/

# Allow search engines to access static assets
Allow: /favicon.ico
Allow: /logo.png
Allow: /apple-touch-icon.png
Allow: /*.css$
Allow: /*.js$
Allow: /*.png$
Allow: /*.jpg$
Allow: /*.jpeg$
Allow: /*.gif$
Allow: /*.svg$
Allow: /*.webp$
Allow: /*.avif$

# Sitemap location
Sitemap: ${baseUrl}/sitemap.xml

# Crawl delay to be respectful
Crawl-delay: 1

# Special instructions for different bots
User-agent: Googlebot
Crawl-delay: 1
Allow: /

User-agent: Bingbot
Crawl-delay: 2
Allow: /

User-agent: facebookexternalhit
Allow: /

User-agent: Twitterbot
Allow: /`

  return new Response(robotsTxt, {
    headers: {
      'Content-Type': 'text/plain',
      'Cache-Control': 'public, max-age=86400, s-maxage=86400', // Cache for 24 hours
    },
  })
}